name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
      env:
        NODE_VERSION: 16.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.5.1
        poetry install
    - name: Run tests
      run: poetry run pytest
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
      env:
        NODE_VERSION: 16.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.5.1
        poetry install
    - name: Run linter
      run: poetry run ruff check .

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
      env:
        NODE_VERSION: 16.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.5.1
        poetry install
    - name: Build project
      run: poetry build